### ISSUE TITLE
Issues on older systems

### ISSUE THREAD

**Issue by throw-n** [MegaManSec/SSH-Snake#6]
Thanks for the script!
Running on older system, there are few syntax problem:

```
root@REDACTED:~# curl https://raw.githubusercontent.com/MegaManSec/SSH-Snake/main/Snake.nocomments.sh | stdbuf -o0 bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
X.X.X.X  X.X.X.X    0     0   259k      0 --:--:-- --:--:-- --:--:--  260k
...
ASCII
...

________________________~_____/^,___,-^\_________________~~_______________/`
|-----------------------------------------|------------------------------|
| Setting                                 | Value                        |
|-----------------------------------------|------------------------------|
| ignore_user                             | 0                            |
| use_sudo                                | 1                            |
| ssh_timeout                             | 3                            |
| retry_count                             | 3                            |
| scan_paths                              |                              |
| scan_paths_depth                        | 3                            |
| interesting_users                       | root root                    |
| interesting_hosts                       | X.X.X.X                    |
| interesting_dests                       |                              |
| ignored_users                           |                              |
| ignored_hosts                           |                              |
| ignored_dests                           |                              |
| ignored_key_files                       | *badcert.pem* *badkey.pem*   |
| custom_cmds                             |                              |
| use_combinate_interesting_users_hosts   | 1                            |
| use_combinate_users_hosts_aggressive    | 0                            |
| use_find_from_hosts                     | 1                            |
| use_find_from_last                      | 1                            |
| use_find_from_authorized_keys           | 1                            |
| use_find_from_known_hosts               | 1                            |
| use_find_from_ssh_config                | 1                            |
| use_find_from_bash_history              | 1                            |
| use_find_arp_neighbours                 | 1                            |
| use_find_d_block                        | 0                            |
| use_find_from_hashed_known_hosts        | 0                            |
| use_find_from_prev_dest                 | 1                            |
| use_find_from_ignore_list               | 0                            |
| use_retry_all_dests                     | 1                            |
|-----------------------------------------|------------------------------|


[X.X.X.X]root@X.X.X.X
[X.X.X.X]root@(X.X.X.X:X.X.X.X:X.X.X.X)
[X.X.X.X]bash: line 205: init_ignored: command not found
[X.X.X.X]bash: line 911: exec_custom_cmds: command not found
[X.X.X.X]root@X.X.X.X: Discovered usable private key in [/root/.ssh/id_rsa]
[X.X.X.X]root@X.X.X.X: EXTERNAL_MSG: KEY[/root/.ssh/id_rsa]: REDACTED
[X.X.X.X]bash: line 553: find_ssh_keys_paths: command not found
[X.X.X.X]bash: line 562: find_d_block: command not found
[X.X.X.X]bash: line 564: find_from_ignore_list: command not found
[X.X.X.X]bash: line 565: find_from_hashed_known_hosts: command not found
[X.X.X.X]bash: line 913: combinate_users_hosts_aggressive: command not found
[X.X.X.X]root@X.X.X.X: EXTERNAL_MSG: INFO: Beginning with 17 dests and 1 keys
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes


---------------------------------------

use_retry_all_dests=1. Re-starting.
3 destinations (from 1 unique servers) added to interesting_dests.

---------------------------------------


[X.X.X.X]root@X.X.X.X
[X.X.X.X]root@(X.X.X.X:X.X.X.X:X.X.X.X)
[X.X.X.X]bash: line 205: init_ignored: command not found
[X.X.X.X]bash: line 735: exec_custom_cmds: command not found
[X.X.X.X]root@X.X.X.X: Discovered usable private key in [/root/.ssh/id_rsa]
[X.X.X.X]root@X.X.X.X: EXTERNAL_MSG: KEY[/root/.ssh/id_rsa]: REDACTED
[X.X.X.X]bash: line 469: find_ssh_keys_paths: command not found
[X.X.X.X]bash: line 473: find_from_authorized_keys: command not found
[X.X.X.X]bash: line 474: find_from_last: command not found
[X.X.X.X]bash: line 475: find_from_known_hosts: command not found
[X.X.X.X]bash: line 476: find_from_hosts: command not found
[X.X.X.X]bash: line 477: find_arp_neighbours: command not found
[X.X.X.X]bash: line 478: find_d_block: command not found
[X.X.X.X]bash: line 479: find_from_prev_dest: command not found
[X.X.X.X]bash: line 480: find_from_ignore_list: command not found
[X.X.X.X]bash: line 481: find_from_hashed_known_hosts: command not found
[X.X.X.X]bash: line 737: combinate_users_hosts_aggressive: command not found
[X.X.X.X]bash: line 738: combinate_interesting_users_hosts: command not found
[X.X.X.X]bash: line 739: deduplicate_resolved_hosts_keys: command not found
[X.X.X.X]root@X.X.X.X: EXTERNAL_MSG: INFO: Beginning with 3 dests and 1 keys
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line: line 0: Bad configuration option: pubkeyacceptedkeytypes



               ______
          _.-""      ""-._
       .-'                `-.
     .'      __.----.__      `.
    /     .-"          "-.        /    .'                `.      J    /                    \    L
  F   J                      L   J
 J    F                      J    L
 |   J                        L   |
 |   |                        |   |
 |   J                        F   |
 J    L                      J    F
  L   J   .-""""-.           F   J
  J    \ /        \   __    /    F
   \    (|)(|)_   .-'".'  .'    /
    \    \   /_>-'  .<_.-'     /
     `.   `-'     .'         .'
       `--.|___.-'`._    _.-'
           ^         """"

           ..             ..
          ( '`<          ( '`<  ...Summary Report:
           )(             )(
    ( ----'  '.    ( ----'  '.
    (         ;    (         ;
     (_______,'     (_______,'
~^~^~^~^~^~^~^~^~^~^~~^~^~^~^~^~^~^~^~^~^~~^~^~^~^~^
Unique private keys discovered: 1
Unique shell accounts accessed: 1
Unique systems accessed: 1

Need a list of servers accessed? Run one of these commands:

grep -oE "[a-z_][a-z0-9_-]{0,31}@[0-9\.]*$" output.log  | sort | uniq
grep -oE "[a-z_][a-z0-9_-]{0,31}@\([0-9\.:]*\)$" output.log  | sort | uniq
-- https://joshua.hu/ --
-- https://github.com/MegaManSec/SSH-Snake --

Thanks for playing!
```

`openssl version`: OpenSSL 1.0.1t  3 May 2016
`bash --version` : GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)

**Comment by MegaManSec** [comment]
Thanks for the report!

I've likely fixed the "Bad configuration option: pubkeyacceptedkeytypes" issue -- please confirm it that's not working.

Can you tell me what OS and version of Awk you are using?

**Comment by throw-n** [comment]
`awk -W version` :  `mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan`
`cat /etc/os-release`
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by throw-n** [comment]
Thanking you for the quick replies.
Now I see:

```|-----------------------------------------|------------------------------|
| Setting                                 | Value                        |
|-----------------------------------------|------------------------------|
| ignore_user                             | 0                            |
| use_sudo                                | 1                            |
| ssh_timeout                             | 3                            |
| retry_count                             | 3                            |
| scan_paths                              |                              |
| scan_paths_depth                        | 3                            |
| interesting_users                       | root root                    |
| interesting_hosts                       | X.X.X.X                    |
| interesting_dests                       |                              |
| ignored_users                           |                              |
| ignored_hosts                           |                              |
| ignored_dests                           |                              |
| ignored_key_files                       | *badcert.pem* *badkey.pem*   |
| custom_cmds                             |                              |
| use_combinate_interesting_users_hosts   | 1                            |
| use_combinate_users_hosts_aggressive    | 0                            |
| use_find_from_hosts                     | 1                            |
| use_find_from_last                      | 1                            |
| use_find_from_authorized_keys           | 1                            |
| use_find_from_known_hosts               | 1                            |
| use_find_from_ssh_config                | 1                            |
| use_find_from_bash_history              | 1                            |
| use_find_arp_neighbours                 | 1                            |
| use_find_d_block                        | 0                            |
| use_find_from_hashed_known_hosts        | 0                            |
| use_find_from_prev_dest                 | 1                            |
| use_find_from_ignore_list               | 0                            |
| use_retry_all_dests                     | 1                            |
|-----------------------------------------|------------------------------|


[X.X.X.X]root@X.X.X.X
[X.X.X.X]root@(X.X.X.X:X.X.X.X:X.X.X.X)
[X.X.X.X]bash: line 207: init_ignored: command not found
[X.X.X.X]bash: line 913: exec_custom_cmds: command not found
[X.X.X.X]root@X.X.X.X: Discovered usable private key in [/root/.ssh/id_rsa]
[X.X.X.X]root@X.X.X.X: EXTERNAL_MSG: KEY[/root/.ssh/id_rsa]: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBd1NIcjNCbkQvTlVaWFo3aktQNXpTdVBvT2xPY2hHVUNhQWc0dlB4VVhTeUZKOGlmCkRMZkFpV0Zac0VrVEVGM09YNldVT1VUZXRHd0wrS0o1RC9DVTh5RnBQWjcvWjY2R25uQWFGMkxJejF1Y0hyU1cKSnJMdjNBUmtNcmlLaE5mTHNCRG9sTnJDL1V6ZFg1ZFloanFoeGxSd3l1Ky9BVUhxbjMrQkhJaHhsVHBlS3RaUgo3b3E5anRTM2l1OFN0UVFNMFlTc1NaNnVQRXFBRWtmSE0xTFRpTFF0Sm1mYVFIdjFNNjdRRXlkbCtTTFpUUTZvCkNsV2lKWXYxSE5wcDg4MjNPSlhXU0E3bGJGSnQ3Z3BBR3N0T2NpdEllNnY3VVhEd29iVFdoWmRmbk5RUlI4Qm8KMWZRaGxya2p6QkgzYlh1bk5rdlIvcW40UkpwUUpibTJ5bGNueHdJREFRQUJBb0lCQUZwaWxLNXlSSDI4QVY0RwpNUXVMWWN1bnM1UXdjeXltMVNSNHpJenRqbEg0dHV4eWdMVUQvaENOUmRzeHA4RmVGV28vNUltVXlLRXBlOFRGCnpPQi8yRVdjMmxMamFXWk5rR1R2MDlZai9oVEZLK0JXNVhxQS9hNDdRK1ZVNWtiYmMxRVg2TEZaWEM0TlhnRVIKcEhWVlZVYXJXQW94ZjNPSU5OU21hSGRCQjk4dEcxRk9FRFZ3TU5uZjloWU1kV2tuZGl0aHB5S1FvNUtUM3ZrMQpkYVVQcnhSa3J2OWs3UHN6cFp6K1podnFtWlJyd3ZmOXcvbnlzVXJtY0tVdHhNZzgySzlZZW9aNFFYZ3AvRExZCi9LaTM4ZDA3dDM4dEFoY3dFRUxzeU9VVDcvaUF1Yk9oem1PRXVuZHAxMGVpYU8zcU1LZG5udHFrZnlrOExhMVkKT1c4NHl6RUNnWUVBK1NqT3B0WDFDL3E0bGRSRFl6MVpnR3R0VUtGODdSaElaZExJbE05a2tNVmVYMlo0RVNiKwpXWFdBOHBWd3YwNW5qVnhHU3NnTzFLMXV4V0dQSDdGVjlBT202RzlZSDE3UG5zdFBZWEZJTGdmOEhGVU1INGZyCklCT3RVQVUwWFMyblJ6eUx6V2I4UDJ0SktCWHFtbUQxM2JzYThoRkR0Q2dTUXhKOUVUZjV2RjhDZ1lFQXhtOVYKbnlvYi8wVENoK0JkcnFMUnhtU0J3YndEOUszc3JBNFFmUGFhaElpeGtFQkNOc0c2a01MK3ZUcUlvK01tOEtubgp1UkRvcnc2eXRrcUU0LzhZeDBEWHRiVVp3L0FFdXVFM01GaExWMU50TEhHajBBaVNibGtuSzBZWVhYTm1vVG5HCmlpMmhPR29WdFY3UktiYmVTa1g2ajVqV01Ca3l4QW1oZDc2elRaa0NnWUEwUUlxV0VtakJpbU1MaU9oWTk1UzkKaWNuekR1clVEak9ncHdQSnNYUzFwNjZTOHpwYTNvS1k0RHVhcEJ4eEFsQlZKUFRZMmZ2Q1BsenNwL2tML0hTNgpKOG5wRlBDMkkzd0hJVHdVZzExUHlmemxORERHckFwelA2MHBDdTVnWENLb25kbnp5WlU4OTVMd0JTaWVGNWQ0CldMVGQ3eUR6dHpPZFBWTmRPUS8yb1FLQmdRREdhZWlaUDhmQzFRUVdUUmdmV0pxYzN6NkhjdklacEJiMGF4TzkKZis4OCtsbGh2WDczdFhwUTZVbEIrTmRMMkFQRnZINEJKSkVsQ1hOVXB1cDk5MExWYVZiSFVCQTFSVGZWalFCYwpETTA0d2loMXVpTnNEa1lzcEdSdjlxVENQSE93WGs3Uk41THZEOVFwQ0dmb1ovdVpGS1BYRmFHRmNveTZURTd4CnB2TXVjUUtCZ0JlRlV2S0tWVFZDOEwxRDMzTzgrTTlocm8rcGlEaVBVb3R0RWJoNzlOMXM2NEU5eTRmRWU4L2sKS3FGajNQRkp4cjF0MHFzOXhTaTNmVzBNSFRkRTVtMy9ES09od0VOampvSXlYTFFEd25Ga1lMVkl0OVExZThaUgppcnZUbWxOSElNRElXNE56WVBieWZSS21ocnBVRktQREREQ2lBY3MzK0c5bG5nVmNMSHRNCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
[X.X.X.X]bash: line 555: find_ssh_keys_paths: command not found
[X.X.X.X]bash: line 564: find_d_block: command not found
[X.X.X.X]bash: line 566: find_from_ignore_list: command not found
[X.X.X.X]bash: line 567: find_from_hashed_known_hosts: command not found
[X.X.X.X]bash: line 915: combinate_users_hosts_aggressive: command not found
[X.X.X.X]root@X.X.X.X: EXTERNAL_MSG: INFO: Beginning with 17 dests and 1 keys
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.


---------------------------------------

use_retry_all_dests=1. Re-starting.
3 destinations (from 1 unique servers) added to interesting_dests.

---------------------------------------


[X.X.X.X]root@X.X.X.X
[X.X.X.X]root@(X.X.X.X:X.X.X.X:X.X.X.X)
[X.X.X.X]bash: line 207: init_ignored: command not found
[X.X.X.X]bash: line 737: exec_custom_cmds: command not found
[X.X.X.X]root@X.X.X.X: Discovered usable private key in [/root/.ssh/id_rsa]
[X.X.X.X]root@X.X.X.X: EXTERNAL_MSG: KEY[/root/.ssh/id_rsa]: REDACTED
[X.X.X.X]bash: line 471: find_ssh_keys_paths: command not found
[X.X.X.X]bash: line 475: find_from_authorized_keys: command not found
[X.X.X.X]bash: line 476: find_from_last: command not found
[X.X.X.X]bash: line 477: find_from_known_hosts: command not found
[X.X.X.X]bash: line 478: find_from_hosts: command not found
[X.X.X.X]bash: line 479: find_arp_neighbours: command not found
[X.X.X.X]bash: line 480: find_d_block: command not found
[X.X.X.X]bash: line 481: find_from_prev_dest: command not found
[X.X.X.X]bash: line 482: find_from_ignore_list: command not found
[X.X.X.X]bash: line 483: find_from_hashed_known_hosts: command not found
[X.X.X.X]bash: line 739: combinate_users_hosts_aggressive: command not found
[X.X.X.X]bash: line 740: combinate_interesting_users_hosts: command not found
[X.X.X.X]bash: line 741: deduplicate_resolved_hosts_keys: command not found
[X.X.X.X]root@X.X.X.X: EXTERNAL_MSG: INFO: Beginning with 3 dests and 1 keys
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
```

**Comment by MegaManSec** [comment]
The issue with the SSH errors should properly be fixed now, please confirm:)

**Comment by MegaManSec** [comment]
Fixed in https://github.com/MegaManSec/SSH-Snake/commit/e0b4cf23a9d9ea8ec71ea27ba90b9775c3834cdc

**Comment by throw-n** [comment]
```
 curl https://raw.githubusercontent.com/MegaManSec/SSH-Snake/main/Snake.nocomments.sh | stdbuf -o0 bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 48440  100 48440    0     0   254k      0 --:--:-- --:--:-- --:--:--  254k
bash: line 1318: unexpected EOF while looking for matching `"'
bash: line 1321: syntax error: unexpected end of file
```

**Comment by MegaManSec** [comment]
It should finally be fixed in https://github.com/MegaManSec/SSH-Snake/commit/92d612fb63e97bf3185642716fc30c06275e3236

**Comment by throw-n** [comment]
@MegaManSec syntax errors now OK, great work !
Still see command line error for algorithm, so script doesn't work, maybe need to switch on ssh version ? 

```
|-----------------------------------------|------------------------------|
| Setting                                 | Value                        |
|-----------------------------------------|------------------------------|
| ignore_user                             | 0                            |
| use_sudo                                | 1                            |
| ssh_timeout                             | 3                            |
| retry_count                             | 3                            |
| scan_paths                              |                              |
| scan_paths_depth                        | 3                            |
| interesting_users                       | root root                    |
| interesting_hosts                       | X.X.X.X                    |
| interesting_dests                       |                              |
| ignored_users                           |                              |
| ignored_hosts                           |                              |
| ignored_dests                           |                              |
| ignored_key_files                       | *badcert.pem* *badkey.pem*   |
| custom_cmds                             |                              |
| use_combinate_interesting_users_hosts   | 1                            |
| use_combinate_users_hosts_aggressive    | 0                            |
| use_find_from_hosts                     | 1                            |
| use_find_from_last                      | 1                            |
| use_find_from_authorized_keys           | 1                            |
| use_find_from_known_hosts               | 1                            |
| use_find_from_ssh_config                | 1                            |
| use_find_from_bash_history              | 1                            |
| use_find_arp_neighbours                 | 1                            |
| use_find_d_block                        | 0                            |
| use_find_from_hashed_known_hosts        | 0                            |
| use_find_from_prev_dest                 | 1                            |
| use_find_from_ignore_list               | 0                            |
| use_retry_all_dests                     | 1                            |
|-----------------------------------------|------------------------------|


[X.X.X.X]root@X.X.X.X
[X.X.X.X]root@(X.X.X.X:X.X.X.X:X.X.X.X)
[X.X.X.X]root@X.X.X.X: Discovered usable private key in [/root/.ssh/id_rsa]
[X.X.X.X]root@X.X.X.X: EXTERNAL_MSG: KEY[/root/.ssh/id_rsa]: REDACTED
[X.X.X.X]root@X.X.X.X: Discovered usable private key in [/root/.ssh/id_rsa_be]
[X.X.X.X]root@X.X.X.X: EXTERNAL_MSG: KEY[/root/.ssh/id_rsa_be]: REDACTED
[X.X.X.X]root@X.X.X.X: EXTERNAL_MSG: INFO: Beginning with 18 dests and 2 keys
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->habib@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->habib@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->habib@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->habib@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.


---------------------------------------

use_retry_all_dests=1. Re-starting.
3 destinations (from 1 unique servers) added to interesting_dests.

---------------------------------------


[X.X.X.X]root@X.X.X.X
[X.X.X.X]root@(X.X.X.X:X.X.X.X:X.X.X.X)
[X.X.X.X]root@X.X.X.X: Discovered usable private key in [/root/.ssh/id_rsa]
[X.X.X.X]root@X.X.X.X: EXTERNAL_MSG: KEY[/root/.ssh/id_rsa]: REDACTED
[X.X.X.X]root@X.X.X.X: Discovered usable private key in [/root/.ssh/id_rsa_be]
[X.X.X.X]root@X.X.X.X: EXTERNAL_MSG: KEY[/root/.ssh/id_rsa_be]: REDACTED
[X.X.X.X]root@X.X.X.X: EXTERNAL_MSG: INFO: Beginning with 3 dests and 2 keys
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: Unsupported KEX algorithm "+diffie-hellman-group1-sha1"
[X.X.X.X] root@X.X.X.X[!/root/.ssh/id_rsa_be]->root@X.X.X.X [line]: command-line line 0: Bad SSH2 KexAlgorithms '+diffie-hellman-group1-sha1'.



               ______
          _.-""      ""-._
       .-'                `-.
     .'      __.----.__      `.
    /     .-"          "-.        /    .'                `.      J    /                    \    L
  F   J                      L   J
 J    F                      J    L
 |   J                        L   |
 |   |                        |   |
 |   J                        F   |
 J    L                      J    F
  L   J   .-""""-.           F   J
  J    \ /        \   __    /    F
   \    (|)(|)_   .-'".'  .'    /
    \    \   /_>-'  .<_.-'     /
     `.   `-'     .'         .'
       `--.|___.-'`._    _.-'
           ^         """"

           ..             ..
          ( '`<          ( '`<  ...Summary Report:
           )(             )(
    ( ----'  '.    ( ----'  '.
    (         ;    (         ;
     (_______,'     (_______,'
~^~^~^~^~^~^~^~^~^~^~~^~^~^~^~^~^~^~^~^~^~~^~^~^~^~^
Unique private keys discovered: 2
Unique shell accounts accessed: 1
Unique systems accessed: 1
``` 

Thanking you

**Comment by MegaManSec** [comment]
Eh, there was a typo, it should be OK now?

**Comment by throw-n** [comment]
Seems very good, thank you.
Very useful tool !

**Comment by MegaManSec** [comment]
Happy to hear it's fixed.
